[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"

# Environment variables para el API
[build.environment]
  VITE_API_URL = "https://serverbackend-8zzp.onrender.com"

