[build]
  command = "cd client && npm install && npm run build"
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/client/dist/index.html"
  status = 200

# Environment variables para el API
[build.environment]
  VITE_API_URL = "https://serverbackend-8zzp.onrender.com"

